### ISSUE TITLE
pkg_resources.RequirementParseError

### ISSUE THREAD

**Issue by sweh** [flyingcircusio/appenv#32]
Hi,

with the newest version of AppEnv, I get a `pkg_resources.RequirementParseError` if the requirement.txt contains a custom index server:

```
# appenv-python-preference: 3.8,3.7
--extra-index-url https://my.custompypi.de/simple
-e .
```

When running `./appenv update-lockfile` I get:

```
Traceback (most recent call last):
  File "./appenv", line 515, in <module>
    main()
  File "./appenv", line 507, in main
    appenv.meta()
  File "./appenv", line 280, in meta
    args.func(args, remaining)
  File "./appenv", line 466, in update_lockfile
    spec = list(pkg_resources.parse_requirements(line))[0]
  File "/Users/sweh/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/Users/sweh/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'--extra-'"
```

Is there another way to specify a custom index server?

**Comment by sweh** [comment]
Fixed with merged PR #33
